-- MySQL Script generated by MySQL Workbench
-- Fri Sep  1 09:53:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema freshcupcoffee
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `freshcupcoffee` ;

-- -----------------------------------------------------
-- Schema freshcupcoffee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `freshcupcoffee` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `freshcupcoffee` ;

-- -----------------------------------------------------
-- Table `freshcupcoffee`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freshcupcoffee`.`item` ;

CREATE TABLE IF NOT EXISTS `freshcupcoffee`.`item` (
  `item_number` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `photo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`item_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freshcupcoffee`.`purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freshcupcoffee`.`purchase` ;

CREATE TABLE IF NOT EXISTS `freshcupcoffee`.`purchase` (
  `purchase_number` INT NOT NULL AUTO_INCREMENT,
  `name_on_card` VARCHAR(255) NULL DEFAULT NULL,
  `credit_card` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `total_price` INT NULL DEFAULT NULL,
  `table_number` INT NULL DEFAULT NULL,
  PRIMARY KEY (`purchase_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freshcupcoffee`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freshcupcoffee`.`order` ;

CREATE TABLE IF NOT EXISTS `freshcupcoffee`.`order` (
  `order_number` INT NOT NULL AUTO_INCREMENT,
  `purchase_number` INT NULL DEFAULT NULL,
  `item_number` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`order_number`),
  INDEX `purchase_number` (`purchase_number` ASC) VISIBLE,
  INDEX `item_number` (`item_number` ASC) VISIBLE,
  CONSTRAINT `item_number`
    FOREIGN KEY (`item_number`)
    REFERENCES `freshcupcoffee`.`item` (`item_number`),
  CONSTRAINT `purchase_number`
    FOREIGN KEY (`purchase_number`)
    REFERENCES `freshcupcoffee`.`purchase` (`purchase_number`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freshcupcoffee`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freshcupcoffee`.`user` ;

CREATE TABLE IF NOT EXISTS `freshcupcoffee`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;